server:
  port: 8080

spring:
  application:
    name: apex-gateway

apex-engine:
  server:
    netty:
      entrypoint:
        port: 8081
  aeron:
    directory-name: /dev/shm/aeron
    channel: aeron:ipc
    stream-id: 10