server:
  port: 9090

spring:
  application:
    name: apex_matching_engine

apex-engine:
  disruptor:
    ring-buffer-size: 4096
  aeron:
    directory-name: /dev/shm/aeron
    channel: aeron:ipc
    stream-id: 10